title: "Gun-Yeal Lee"
author: "Gun-Yeal Lee"
description: "Gun-Yeal Lee" #"Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "index.html"}
  # - {file: "README.md"}

# Menu (in pages subfolder)

navigation:
  - title: "CV"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
  # - title: "Publications2"
  #   url: "/publications2/"

    

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gunyeal@stanford.edu"}
  # - {title: Github, icon: github, url: "https://github.com/gunyeal"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=SlXpVNkAAAAJ&hl=en"}
  - {title: Linked In, icon: linkedin, url: "https://www.linkedin.com/in/gun-yeal-lee-4b7b54224"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
